=== davudmurtazin/Task8/src/by/epam/task8/schema/cars-schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 	xmlns="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.car-shop.com/cars"
           xmlns:tns="http://www.car-shop.com/cars"
           elementFormDefault="qualified">

    <element name="cars">
        <complexType>
            <sequence>
                <element name="car" type="tns:car" minOccurs="0" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="car">
        <sequence>
            <element name="mark" type="string" />
            <element name="title" type="string" />
            <element name="number" type="string" />
            <element name="color" type="string" />
            <element name="price" type="string" />
        </sequence>
        <attribute name="type" type="string"/>
    </complexType>
</schema>

=== davudmurtazin/Task8/src/by/epam/task8/xml/xmlCars.xml
<?xml version="1.0" encoding="UTF-8"?>
<cars xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xmlns="http://www.car-shop.com/cars"
      xsi:schemaLocation="http://www.car-shop.com/cars  /by/epam/task8/schema/cars-schema.xsd">
    <car type = "sport">
        <mark>Mitsubishi</mark>
        <title>Lancer</title>
        <number>CA2145</number>
        <color>red</color>
        <price>21000</price>
    </car>
    <car type = "luxury">
        <mark>Mersedes</mark>
        <title>S500</title>
        <number>NY4541</number>
        <color>black</color>
        <price>35000</price>
    </car>
    <car type = "economic">
        <mark>Hyundai</mark>
        <title>Solaris</title>
        <number>CH5465</number>
        <color>white</color>
        <price>5000</price>
    </car>
    <car type = "Compact">
        <mark>Mini</mark>
        <title>Cooper</title>
        <number>AP4587</number>
        <color>grey</color>
        <price>12100</price>
    </car>
</cars>
